### ISSUE TITLE
make 

### ISSUE THREAD

**Issue by Mmagdy1** [kuzmin-no/nrf-research-firmware-python3#1]
any idea for below error , Iam using kali linux 

sdcc --model-large --std-c99 -c src/main.c -o bin/main.rel
sdcc --model-large --std-c99 -c src/usb.c -o bin/usb.rel
sdcc --model-large --std-c99 -c src/usb_desc.c -o bin/usb_desc.rel
sdcc --model-large --std-c99 -c src/radio.c -o bin/radio.rel
sdcc --xram-loc 0x8000 --xram-size 2048 --model-large bin/main.rel bin/usb.rel bin/usb_desc.rel bin/radio.rel -o bin/dongle.ihx
objcopy -I ihex bin/dongle.ihx -O binary bin/dongle.bin
objcopy --pad-to 26622 --gap-fill 255 -I ihex bin/dongle.ihx -O binary bin/dongle.formatted.bin
objcopy -I binary bin/dongle.formatted.bin -O ihex bin/dongle.formatted.ihx

**Comment by kuzmin-no** [comment]
This is not an error, that was output of **make** command.
The firmware was succesfully compiled and located in file **bin/dongle.formatted.ihx**
